### PR TITLE
[ENH] Add auto-complete and target specification 

### PR DESCRIPTION
**Pull request by alexrockhill**
Depends on https://github.com/mne-tools/mne-gui-addons/pull/20.

With the target coordinates, the task of marking each contact is quite boring and seems not too hard to automate. Here is a shot at it that is close but needs a bit of fine-tuning still. The algorithm:

- Finds a local maximum near the target
- Does a forward pass in the direction of the electrode
- Does a backward pass in case the second contact was selected accidentally

I'm running into issues with false-positives which I need to look into. Possibly the radius just has to be set higher.

I think this will help save a lot of time.

### CODE REVIEW

**Comment by alexrockhill** [comment]
It's not perfect but this is a very good start. Should save a ton of time for marking contacts. I need to add a simple test but then it's ready to go. The real test is in building the examples that it works for sEEG and ECoG which I tested and it looks like it works really well. Will add that soon.

**Comment by alexrockhill** [comment]
@larsoner would these failures happen to be related anything that you touched in mne-python lately?

**Comment by larsoner** [comment]
You'll want to follow https://github.com/mne-tools/mne-python/pull/12251

**Comment by alexrockhill** [comment]
Okay this is ready to merge by me, it's not perfect but it's pretty close. It automatically marks ~20 sEEG contacts and an entire 256 grid perfectly which is a huge time-saver. I added tests as well but they just check the API since that would be a lot of contacts to mock.

**Comment by alexrockhill** [comment]
Looks great, ready to merge: https://output.circle-artifacts.com/output/job/7614b75f-9bc0-4d8e-a59b-983dfdbead6d/artifacts/0/dev/auto_examples/ieeg_locate.html

There is an unrelated issue where the scraper takes a screenshot of the brains before the `show_view` call takes effect. I'll fix that in a followup PR.

**Comment by larsoner** [comment]
> Could you set those for me please?

Instead I made you a maintainer :)

**Comment by larsoner** [comment]
> EDIT: I looked and I'm not really sure how to fix that, anyone know how?

In theory doing [`brain.show_view` should call `update=True`](https://mne.tools/stable/generated/mne.viz.Brain.html#mne.viz.Brain.show_view), which should cause it to update before the screenshot happens. You could try adding a `plotter.render()` (or maybe it's `update()`? can't remember) to the scraper to see if it helps

**Comment by alexrockhill** [comment]
> > EDIT: I looked and I'm not really sure how to fix that, anyone know how?
> 
> In theory doing [`brain.show_view` should call `update=True`](https://mne.tools/stable/generated/mne.viz.Brain.html#mne.viz.Brain.show_view), which should cause it to update before the screenshot happens. You could try adding a `plotter.render()` (or maybe it's `update()`? can't remember) to the scraper to see if it helps

```
for brain in list(block_vars["example_globals"].values()):
    # Only need to process if it's a brain with a time_viewer
    # with traces on and shown in the same window, otherwise
    # PyVista and matplotlib scrapers can just do the work
```

Looks like maybe without a time viewer it just gets scraped by `pyvista`... Not sure how to proceed there.

**Comment by alexrockhill** [comment]
Okay to merge?

I'll follow-up with a PR on the scraper if I can figure that out. Maybe I'll just raise an issue on pyvista to start.

**Pull request merged**
