### PR TITLE
[ENH] Use scanner RAS instead of surface RAS in textbox

### PR DESCRIPTION
**Pull request by alexrockhill**

### CODE REVIEW

**Comment by alexrockhill** [comment]
image

image

Currently on `main` it looks like voxels actually aren't correct so I'm going to fix that and add to this PR before merging

**Comment by alexrockhill** [comment]
Notes to self/others:

Here's the problem; if you have surgical plans according to an MRI/CT/merged MRCT, you probably have the target locations for the sEEG electrodes in voxels or scanner RAS. Currently, the voxel textbox is RAS voxels, not native voxels to the image and the RAS textbox is surface RAS. This PR:

- Sets the RAS textbox to scanner RAS
- Sets the voxel textbox to raw voxels
- Uses surface RAS for 3D rendering and to store channel positions before applying the head->mri trans (only internal)
- Otherwise uses scanner RAS as the internal coordiante system and routes everything through that for simplicity (relatively speaking)

Note also includes small fix for zoom.

Note none of previous positions are wrong, you just can't access normal voxels or scanner RAS coordinates.

**Comment by alexrockhill** [comment]
Here's a MWE stretching the minimum part a bit:

```
import numpy as np
import mne
import mne_gui_addons as mne_gui
from mne.datasets import somato
from mne.time_frequency import csd_tfr

data_path = somato.data_path()
subject = '01'
task = 'somato'
raw_fname = (data_path / 'sub-{}'.format(subject) / 'meg' /
             'sub-{}_task-{}_meg.fif'.format(subject, task))

# crop to 5 minutes to save memory
raw = mne.io.read_raw_fif(raw_fname).crop(0, 300)
raw.load_data()

# the DICS beamformer currently only supports a single sensor type,
# we'll use the gradiometers in this example
picks = mne.pick_types(raw.info, meg='grad', eog=True, exclude='bads')

# read epochs
events = mne.find_events(raw)
epochs = mne.Epochs(raw, events, event_id=1, tmin=-1.5, tmax=2, picks=picks,
                    preload=True, decim=3)

# read forward operator and point to freesurfer subject directory
fname_fwd = (data_path / 'derivatives' / 'sub-{}'.format(subject) /
             'sub-{}_task-{}-fwd.fif'.format(subject, task))
subjects_dir = data_path / 'derivatives' / 'freesurfer' / 'subjects'

fwd = mne.read_forward_solution(fname_fwd)

rank = mne.compute_rank(epochs, tol=1e-6, tol_kind='relative')
active_win = (0.5, 1.5)
baseline_win = (-1, 0)

# compute cross-spectral density matrices
freqs = np.logspace(np.log10(12), np.log10(30), 9)

# time-frequency decomposition
epochs_tfr = mne.time_frequency.tfr_morlet(
    epochs, freqs=freqs, n_cycles=freqs / 2, return_itc=False,
    average=False, output='complex')
epochs_tfr.decimate(20)  # decimate for speed

csd = csd_tfr(epochs_tfr, tmin=-1, tmax=1.5)
baseline_csd = csd_tfr(epochs_tfr, tmin=baseline_win[0], tmax=baseline_win[1])
ers_csd = csd_tfr(epochs_tfr, tmin=active_win[0], tmax=active_win[1])

surface = subjects_dir / subject / 'bem' / 'inner_skull.surf'
vol_src = mne.setup_volume_source_space(
    subject=subject, subjects_dir=subjects_dir, surface=surface,
    pos=10, add_interpolator=False)  # just for speed!

conductivity = (0.3,)  # one layer for MEG
model = mne.make_bem_model(subject=subject, ico=3,  # just for speed
                           conductivity=conductivity,
                           subjects_dir=subjects_dir)
bem = mne.make_bem_solution(model)

trans = fwd['info']['mri_head_t']
vol_fwd = mne.make_forward_solution(
    raw.info, trans=trans, src=vol_src, bem=bem, meg=True, eeg=True,
    mindist=5.0, n_jobs=1, verbose=True)

# Compute source estimate using MNE solver
snr = 3.0
lambda2 = 1.0 / snr ** 2
method = 'MNE'  # use MNE method (could also be dSPM or sLORETA)

# make a different inverse operator for each frequency so as to properly
# whiten the sensor data
inverse_operator = list()
for freq_idx in range(epochs_tfr.freqs.size):
    # for each frequency, compute a separate covariance matrix
    baseline_cov = baseline_csd.get_data(index=freq_idx, as_cov=True)
    baseline_cov['data'] = baseline_cov['data'].real  # only normalize by real
    # then use that covariance matrix as normalization for the inverse
    # operator
    inverse_operator.append(mne.minimum_norm.make_inverse_operator(
        epochs.info, vol_fwd, baseline_cov))

# finally, compute the stcs for each epoch and frequency
stcs = mne.minimum_norm.apply_inverse_tfr_epochs(
    epochs_tfr, inverse_operator, lambda2, method=method,
    pick_ori='vector')

viewer = mne_gui.view_vol_stc(stcs, subject=subject, subjects_dir=subjects_dir,
                              src=vol_src, inst=epochs_tfr)
viewer.go_to_extreme()  # show the maximum intensity source vertex
viewer.set_cmap(vmin=0.25, vmid=0.8)
viewer.set_3d_view(azimuth=40, elevation=35, distance=300)
```

**Comment by alexrockhill** [comment]
I did some quick testing and I think this is ready to go but it took a lot longer than I thought and got a bit late so I'll test more thoroughly later and confirm everything works as expected.

**Comment by alexrockhill** [comment]
Lastly, here is that same example from above now but note that the RAS and voxels match freesurfer.

image

image

**Review by agramfort — APPROVED** [review]

**Comment by alexrockhill** [comment]
Gave it a closer look in the light of day (figuratively, it's not actually light), looks good to go by me

**Review by larsoner — COMMENTED** [review]
Seems reasonable to me.

At some point we might consider changing the naming to match MNE-Python, where "mri" means "surface RAS", "ras" means "scanner RAS". It seems like you have a different convention here where "ras" means "surface RAS" and "scan_ras" means "scanner RAS"

**Comment by alexrockhill** [comment]
Thanks for merging.

Yes, in the transforms, I have `xxx_ras_t` to mean surface RAS. I can fix that in a followup. User-facing, the RAS in the bottom right corner is scanner RAS so I think that's okay.

**Pull request merged**
